### ISSUE TITLE
Did you run out of spare time?

### ISSUE THREAD

**Issue by StuartIanNaylor** [bridadan/libsnapcast#2]
Would be great dunno if anyone else has but the client would be cool especially with the new esp32-s3 or PS ram models.

**Comment by bridadan** [comment]
Haha sure feels like I've ran out of spare time lately!

Every so often I poke around it some more, but I don't see me seriously continuing it in the future.

I do know a few other people continued working on it and took it a bit farther. The main discussion was here: https://github.com/badaix/snapcast/issues/22

@jorgenkraghjakobsen created a client here: https://github.com/jorgenkraghjakobsen/snapclient

Honestly, an idea that intrigues me more is making a project that speaks directly to pulseaudio or pipewire and becomes a networked audio device for the Linux system. Both for audio output and input (through a mic). We'll see if I ever get to that though, lots of work to do there I think
